name: Hello World at 2:10 PM IST

on:
  schedule:
    - cron: '23 13 * * *'  # UTC time (08:40 UTC = 14:10 IST)
  workflow_dispatch:  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
