name: Hello World at 2:10 PM IST

on:
  schedule:
    - cron: '53 16 * * *'
    - cron: '10 9 * * *'
  workflow_dispatch:  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
